[package]
name = "nebulousengine"
version = "0.0.1"
edition = "2021"

[dependencies]
# bevy
bevy = "0.10.1"

# egui
bevy_egui = "0.20"
egui = "0.21"

# json
json = "0.12.4"

# internal
nebulousengine_editor = { path = "./crates/editor" }
nebulousengine_entities = { path = "./crates/entities" }
nebulousengine_input = { path = "./crates/input" }
nebulousengine_scenes = { path = "./crates/scenes" }
nebulousengine_ui = { path = "./crates/ui" }
nebulousengine_utils = { path = "./crates/utils" }
