[package]
name = "nebulousengine_noneditor"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy = "0.10.1"

# json
json = "0.12.4"

nebulousengine_utils = { path = "../utils" }
nebulousengine_scenes = { path = "../scenes" }
nebulousengine_input = { path = "../input" }