[package]
name = "nebulousengine_networking"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.0"

# serde
serde = "1.0.183"
serde_json = "1.0.105"

# networking
url = "2.4.0"
tungstenite = "0.20.0"